# Generated by Django 5.0.7 on 2024-09-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_offer_options_offer_image_alter_product_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="image",
            field=models.ImageField(upload_to="offer/images", verbose_name="image"),
        ),
    ]
