# Generated by Django 5.0.7 on 2024-09-16 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_offer_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CouponCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="name"),
                ),
                ("percent", models.FloatField(verbose_name="percent")),
                ("start_time", models.DateTimeField(verbose_name="start time")),
                ("end_time", models.DateTimeField(verbose_name="end time")),
                (
                    "quantity",
                    models.PositiveBigIntegerField(default=1, verbose_name="quantity"),
                ),
                (
                    "minimum_purchase",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="minimum purchase"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "product",
                    models.ManyToManyField(
                        related_name="coupon_code",
                        to="product.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "user",
                    models.ManyToManyField(
                        related_name="coupon_code",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon Code",
                "verbose_name_plural": "Coupon Codes",
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
    ]
