# Generated by Django 5.0.7 on 2024-08-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Otp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=11, verbose_name="phone")),
                (
                    "random_code",
                    models.CharField(max_length=5, verbose_name="random code"),
                ),
                ("token", models.CharField(max_length=255, verbose_name="token")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
        ),
    ]
